<?php
declare(strict_types=1);

namespace Iahunter\JuniperMist\Models;

use Iahunter\JuniperMist\Models\BaseModel;

class WlanPortalTemplateSetting extends BaseModel
{
    public string $accessCodeAlternateEmail;
    public $alignment;
    public $ar;
    public string $authButtonAmazon;
    public string $authButtonAzure;
    public string $authButtonEmail;
    public string $authButtonFacebook;
    public string $authButtonGoogle;
    public string $authButtonMicrosoft;
    public string $authButtonPassphrase;
    public string $authButtonSms;
    public string $authButtonSponsor;
    public string $authLabel;
    public string $backLink;
    public $ca-ES;
    public string $color;
    public string $colorDark;
    public string $colorLight;
    public bool $company;
    public string $companyError;
    public string $companyLabel;
    public $cs-CZ;
    public $da-DK;
    public $de-DE;
    public $el-GR;
    public bool $email;
    public string $emailAccessDomainError;
    public string $emailCancel;
    public string $emailCodeCancel;
    public string $emailCodeError;
    public string $emailCodeFieldLabel;
    public string $emailCodeMessage;
    public string $emailCodeSubmit;
    public string $emailCodeTitle;
    public string $emailError;
    public string $emailFieldLabel;
    public string $emailLabel;
    public string $emailMessage;
    public string $emailSubmit;
    public string $emailTitle;
    public $en-GB;
    public $en-US;
    public $es-ES;
    public $fi-FI;
    public bool $field1;
    public string $field1Error;
    public string $field1Label;
    public bool $field1Required;
    public bool $field2;
    public string $field2Error;
    public string $field2Label;
    public bool $field2Required;
    public bool $field3;
    public string $field3Error;
    public string $field3Label;
    public bool $field3Required;
    public bool $field4;
    public string $field4Error;
    public string $field4Label;
    public bool $field4Required;
    public $fr-FR;
    public $he-IL;
    public $hi-IN;
    public $hr-HR;
    public $hu-HU;
    public $id-ID;
    public $it-IT;
    public $ja-JP;
    public $ko-KR;
    public string $logo;
    public int $logoHeight;
    public int $logoWidth;
    public string $marketingPolicyLink;
    public bool $marketingPolicyOptIn;
    public string $marketingPolicyOptInLabel;
    public string $marketingPolicyOptInText;
    public string $message;
    public $ms-MY;
    public bool $multiAuth;
    public bool $name;
    public string $nameError;
    public string $nameLabel;
    public $nb-NO;
    public $nl-NL;
    public bool $optOutDefault;
    public bool $optout;
    public string $optoutLabel;
    public string $pageTitle;
    public string $passphraseCancel;
    public string $passphraseError;
    public string $passphraseLabel;
    public string $passphraseMessage;
    public string $passphraseSubmit;
    public string $passphraseTitle;
    public $pl-PL;
    public bool $poweredBy;
    public bool $privacy;
    public string $privacyPolicyAcceptLabel;
    public string $privacyPolicyError;
    public string $privacyPolicyLink;
    public string $privacyPolicyText;
    public $pt-BR;
    public $pt-PT;
    public string $requiredFieldLabel;
    public bool $responsiveLayout;
    public $ro-RO;
    public $ru-RU;
    public string $signInLabel;
    public $sk-SK;
    public string $smsCarrierDefault;
    public string $smsCarrierError;
    public string $smsCarrierFieldLabel;
    public string $smsCodeCancel;
    public string $smsCodeError;
    public string $smsCodeFieldLabel;
    public string $smsCodeMessage;
    public string $smsCodeSubmit;
    public string $smsCodeTitle;
    public string $smsCountryFieldLabel;
    public string $smsCountryFormat;
    public string $smsHaveAccessCode;
    public bool $smsIsTwilio;
    public string $smsMessageFormat;
    public string $smsNumberCancel;
    public string $smsNumberError;
    public string $smsNumberFieldLabel;
    public string $smsNumberFormat;
    public string $smsNumberMessage;
    public string $smsNumberSubmit;
    public string $smsNumberTitle;
    public string $smsUsernameFormat;
    public int $smsValidityDuration;
    public string $sponsorBackLink;
    public string $sponsorCancel;
    public string $sponsorEmail;
    public string $sponsorEmailError;
    public string $sponsorEmailTemplate;
    public string $sponsorInfoApproved;
    public string $sponsorInfoDenied;
    public string $sponsorInfoPending;
    public string $sponsorName;
    public string $sponsorNameError;
    public string $sponsorNotePending;
    public string $sponsorRequestAccess;
    public string $sponsorStatusApproved;
    public string $sponsorStatusDenied;
    public string $sponsorStatusPending;
    public string $sponsorSubmit;
    public string $sponsorsError;
    public string $sponsorsFieldLabel;
    public $sv-SE;
    public $th-TH;
    public bool $tos;
    public string $tosAcceptLabel;
    public string $tosError;
    public string $tosLink;
    public string $tosText;
    public $tr-TR;
    public $uk-UA;
    public $vi-VN;
    public $zh-Hans;
    public $zh-Hant;

    public function __construct(array $data = [])
    {
        foreach ($data as $k => $v) {
            if (property_exists($this, $k)) {
                $this->$k = $v;
            }
        }
    }
}