<?php
declare(strict_types=1);

namespace Iahunter\JuniperMist;

use Iahunter\JuniperMist\Http\HttpClient;

use Iahunter\JuniperMist\Apis\ConstantsEventsApi;
use Iahunter\JuniperMist\Apis\ConstantsDefinitionsApi;
use Iahunter\JuniperMist\Apis\ConstantsModelsApi;
use Iahunter\JuniperMist\Apis\InstallerApi;
use Iahunter\JuniperMist\Apis\AdminsApi;
use Iahunter\JuniperMist\Apis\AdminsLoginApi;
use Iahunter\JuniperMist\Apis\AdminsLookupApi;
use Iahunter\JuniperMist\Apis\AdminsLoginOauth2Api;
use Iahunter\JuniperMist\Apis\AdminsLogoutApi;
use Iahunter\JuniperMist\Apis\OrgsSdkInvitesApi;
use Iahunter\JuniperMist\Apis\MspsApi;
use Iahunter\JuniperMist\Apis\MspsAdminsApi;
use Iahunter\JuniperMist\Apis\MspsLicensesApi;
use Iahunter\JuniperMist\Apis\MspsSlesApi;
use Iahunter\JuniperMist\Apis\MspsInventoryApi;
use Iahunter\JuniperMist\Apis\MspsLogoApi;
use Iahunter\JuniperMist\Apis\MspsLogsApi;
use Iahunter\JuniperMist\Apis\MspsOrgGroupsApi;
use Iahunter\JuniperMist\Apis\MspsOrgsApi;
use Iahunter\JuniperMist\Apis\MspsSsoRolesApi;
use Iahunter\JuniperMist\Apis\MspsSsoApi;
use Iahunter\JuniperMist\Apis\MspsMarvisApi;
use Iahunter\JuniperMist\Apis\MspsTicketsApi;
use Iahunter\JuniperMist\Apis\OrgsApi;
use Iahunter\JuniperMist\Apis\OrgsDevicesSsrApi;
use Iahunter\JuniperMist\Apis\OrgsAdvancedAntiMalwareProfilesApi;
use Iahunter\JuniperMist\Apis\OrgsAdminsApi;
use Iahunter\JuniperMist\Apis\OrgsAlarmsApi;
use Iahunter\JuniperMist\Apis\OrgsAlarmTemplatesApi;
use Iahunter\JuniperMist\Apis\OrgsApiTokensApi;
use Iahunter\JuniperMist\Apis\OrgsApTemplatesApi;
use Iahunter\JuniperMist\Apis\OrgsAssetFiltersApi;
use Iahunter\JuniperMist\Apis\OrgsAssetsApi;
use Iahunter\JuniperMist\Apis\OrgsAntivirusProfilesApi;
use Iahunter\JuniperMist\Apis\OrgsCertApi;
use Iahunter\JuniperMist\Apis\OrgsLicensesApi;
use Iahunter\JuniperMist\Apis\OrgsClientsWirelessApi;
use Iahunter\JuniperMist\Apis\UtilitiesWiFiApi;
use Iahunter\JuniperMist\Apis\OrgsCrlApi;
use Iahunter\JuniperMist\Apis\OrgsDeviceProfilesApi;
use Iahunter\JuniperMist\Apis\OrgsDevicesApi;
use Iahunter\JuniperMist\Apis\UtilitiesUpgradeApi;
use Iahunter\JuniperMist\Apis\OrgsEventsApi;
use Iahunter\JuniperMist\Apis\OrgsEvpnTopologiesApi;
use Iahunter\JuniperMist\Apis\OrgsGatewayTemplatesApi;
use Iahunter\JuniperMist\Apis\OrgsGuestsApi;
use Iahunter\JuniperMist\Apis\OrgsIdpProfilesApi;
use Iahunter\JuniperMist\Apis\OrgsSlesApi;
use Iahunter\JuniperMist\Apis\OrgsInventoryApi;
use Iahunter\JuniperMist\Apis\OrgsJsiApi;
use Iahunter\JuniperMist\Apis\OrgsLogsApi;
use Iahunter\JuniperMist\Apis\OrgsMapsApi;
use Iahunter\JuniperMist\Apis\OrgsMarvisInvitesApi;
use Iahunter\JuniperMist\Apis\OrgsNacIdpApi;
use Iahunter\JuniperMist\Apis\OrgsMxclustersApi;
use Iahunter\JuniperMist\Apis\OrgsMxedgesApi;
use Iahunter\JuniperMist\Apis\OrgsMxtunnelsApi;
use Iahunter\JuniperMist\Apis\OrgsClientsNacApi;
use Iahunter\JuniperMist\Apis\OrgsNacPortalsApi;
use Iahunter\JuniperMist\Apis\OrgsNacRulesApi;
use Iahunter\JuniperMist\Apis\OrgsNacTagsApi;
use Iahunter\JuniperMist\Apis\OrgsNetworksApi;
use Iahunter\JuniperMist\Apis\OrgsNetworkTemplatesApi;
use Iahunter\JuniperMist\Apis\OrgsDevicesOthersApi;
use Iahunter\JuniperMist\Apis\UtilitiesPcapsApi;
use Iahunter\JuniperMist\Apis\OrgsPremiumAnalyticsApi;
use Iahunter\JuniperMist\Apis\OrgsPskPortalsApi;
use Iahunter\JuniperMist\Apis\OrgsPsksApi;
use Iahunter\JuniperMist\Apis\OrgsRfTemplatesApi;
use Iahunter\JuniperMist\Apis\OrgsClientsSdkApi;
use Iahunter\JuniperMist\Apis\OrgsSdkTemplatesApi;
use Iahunter\JuniperMist\Apis\OrgsSecintelProfilesApi;
use Iahunter\JuniperMist\Apis\OrgsSecurityPoliciesApi;
use Iahunter\JuniperMist\Apis\OrgsServicePoliciesApi;
use Iahunter\JuniperMist\Apis\OrgsServicesApi;
use Iahunter\JuniperMist\Apis\OrgsSettingApi;
use Iahunter\JuniperMist\Apis\OrgsIntegrationCradlepointApi;
use Iahunter\JuniperMist\Apis\OrgsIntegrationJseApi;
use Iahunter\JuniperMist\Apis\OrgsIntegrationJuniperApi;
use Iahunter\JuniperMist\Apis\OrgsNacCrlApi;
use Iahunter\JuniperMist\Apis\OrgsScepApi;
use Iahunter\JuniperMist\Apis\OrgsIntegrationSkyatpApi;
use Iahunter\JuniperMist\Apis\OrgsIntegrationZscalerApi;
use Iahunter\JuniperMist\Apis\OrgsLinkedApplicationsApi;
use Iahunter\JuniperMist\Apis\OrgsSitegroupsApi;
use Iahunter\JuniperMist\Apis\OrgsSitesApi;
use Iahunter\JuniperMist\Apis\OrgsSiteTemplatesApi;
use Iahunter\JuniperMist\Apis\OrgsSsoRolesApi;
use Iahunter\JuniperMist\Apis\OrgsSsoApi;
use Iahunter\JuniperMist\Apis\OrgsStatsApi;
use Iahunter\JuniperMist\Apis\OrgsStatsAssetsApi;
use Iahunter\JuniperMist\Apis\OrgsStatsBgpPeersApi;
use Iahunter\JuniperMist\Apis\OrgsStatsDevicesApi;
use Iahunter\JuniperMist\Apis\OrgsClientsMarvisApi;
use Iahunter\JuniperMist\Apis\OrgsStatsMxedgesApi;
use Iahunter\JuniperMist\Apis\OrgsStatsOtherDevicesApi;
use Iahunter\JuniperMist\Apis\OrgsStatsPortsApi;
use Iahunter\JuniperMist\Apis\OrgsStatsSitesApi;
use Iahunter\JuniperMist\Apis\OrgsStatsTunnelsApi;
use Iahunter\JuniperMist\Apis\OrgsStatsVpnPeersApi;
use Iahunter\JuniperMist\Apis\OrgsWlanTemplatesApi;
use Iahunter\JuniperMist\Apis\OrgsTicketsApi;
use Iahunter\JuniperMist\Apis\OrgsMarvisApi;
use Iahunter\JuniperMist\Apis\OrgsUiSettingsApi;
use Iahunter\JuniperMist\Apis\OrgsUserMacsApi;
use Iahunter\JuniperMist\Apis\OrgsVarsApi;
use Iahunter\JuniperMist\Apis\OrgsVpnsApi;
use Iahunter\JuniperMist\Apis\OrgsClientsWanApi;
use Iahunter\JuniperMist\Apis\OrgsWebhooksApi;
use Iahunter\JuniperMist\Apis\OrgsClientsWiredApi;
use Iahunter\JuniperMist\Apis\UtilitiesLanApi;
use Iahunter\JuniperMist\Apis\OrgsWlansApi;
use Iahunter\JuniperMist\Apis\OrgsWxrulesApi;
use Iahunter\JuniperMist\Apis\OrgsWxtagsApi;
use Iahunter\JuniperMist\Apis\OrgsWxtunnelsApi;
use Iahunter\JuniperMist\Apis\AdminsRecoverPasswordApi;
use Iahunter\JuniperMist\Apis\SelfAccountApi;
use Iahunter\JuniperMist\Apis\SelfApiTokenApi;
use Iahunter\JuniperMist\Apis\SelfAuditLogsApi;
use Iahunter\JuniperMist\Apis\SelfOauth2Api;
use Iahunter\JuniperMist\Apis\SelfAlarmsApi;
use Iahunter\JuniperMist\Apis\SelfMfaApi;
use Iahunter\JuniperMist\Apis\SitesApi;
use Iahunter\JuniperMist\Apis\SitesAdvancedAntiMalwareProfilesApi;
use Iahunter\JuniperMist\Apis\SitesAlarmsApi;
use Iahunter\JuniperMist\Apis\SitesSpectrumAnalysisApi;
use Iahunter\JuniperMist\Apis\SitesAnomalyApi;
use Iahunter\JuniperMist\Apis\SitesApplicationsApi;
use Iahunter\JuniperMist\Apis\SitesApTemplatesApi;
use Iahunter\JuniperMist\Apis\SitesAssetFiltersApi;
use Iahunter\JuniperMist\Apis\SitesAssetsApi;
use Iahunter\JuniperMist\Apis\SitesAntivirusProfilesApi;
use Iahunter\JuniperMist\Apis\SitesBeaconsApi;
use Iahunter\JuniperMist\Apis\SitesClientsWirelessApi;
use Iahunter\JuniperMist\Apis\SitesDeviceProfilesApi;
use Iahunter\JuniperMist\Apis\SitesDevicesApi;
use Iahunter\JuniperMist\Apis\SitesDevicesWirelessApi;
use Iahunter\JuniperMist\Apis\UtilitiesCommonApi;
use Iahunter\JuniperMist\Apis\UtilitiesLocationApi;
use Iahunter\JuniperMist\Apis\SitesSyntheticTestsApi;
use Iahunter\JuniperMist\Apis\UtilitiesWanApi;
use Iahunter\JuniperMist\Apis\SitesDevicesWanClusterApi;
use Iahunter\JuniperMist\Apis\SitesDevicesWiredApi;
use Iahunter\JuniperMist\Apis\SitesDevicesWiredVirtualChassisApi;
use Iahunter\JuniperMist\Apis\SitesEventsApi;
use Iahunter\JuniperMist\Apis\SitesEvpnTopologiesApi;
use Iahunter\JuniperMist\Apis\SitesGatewayTemplatesApi;
use Iahunter\JuniperMist\Apis\SitesGuestsApi;
use Iahunter\JuniperMist\Apis\SitesIdpProfilesApi;
use Iahunter\JuniperMist\Apis\SitesInsightsApi;
use Iahunter\JuniperMist\Apis\OrgsNacFingerprintsApi;
use Iahunter\JuniperMist\Apis\SitesRoguesApi;
use Iahunter\JuniperMist\Apis\SitesLicensesApi;
use Iahunter\JuniperMist\Apis\SitesLocationApi;
use Iahunter\JuniperMist\Apis\SitesMapsApi;
use Iahunter\JuniperMist\Apis\SitesMapsAutoPlacementApi;
use Iahunter\JuniperMist\Apis\SitesMapsAutoZoneApi;
use Iahunter\JuniperMist\Apis\SitesMxedgesApi;
use Iahunter\JuniperMist\Apis\UtilitiesMxedgeApi;
use Iahunter\JuniperMist\Apis\SitesClientsNacApi;
use Iahunter\JuniperMist\Apis\SitesNetworksApi;
use Iahunter\JuniperMist\Apis\SitesNetworkTemplatesApi;
use Iahunter\JuniperMist\Apis\SitesDevicesOthersApi;
use Iahunter\JuniperMist\Apis\SitesPsksApi;
use Iahunter\JuniperMist\Apis\SitesRfdiagsApi;
use Iahunter\JuniperMist\Apis\SitesRfTemplatesApi;
use Iahunter\JuniperMist\Apis\SitesRrmApi;
use Iahunter\JuniperMist\Apis\SitesRssiZonesApi;
use Iahunter\JuniperMist\Apis\SitesSecintelProfilesApi;
use Iahunter\JuniperMist\Apis\SitesServicePoliciesApi;
use Iahunter\JuniperMist\Apis\SitesServicesApi;
use Iahunter\JuniperMist\Apis\SitesSettingApi;
use Iahunter\JuniperMist\Apis\SitesJseApi;
use Iahunter\JuniperMist\Apis\SitesSiteTemplatesApi;
use Iahunter\JuniperMist\Apis\SitesSkyatpApi;
use Iahunter\JuniperMist\Apis\SitesSlesApi;
use Iahunter\JuniperMist\Apis\SitesStatsApi;
use Iahunter\JuniperMist\Apis\SitesStatsAppsApi;
use Iahunter\JuniperMist\Apis\SitesStatsAssetsApi;
use Iahunter\JuniperMist\Apis\SitesStatsBeaconsApi;
use Iahunter\JuniperMist\Apis\SitesStatsBgpPeersApi;
use Iahunter\JuniperMist\Apis\SitesStatsCallsApi;
use Iahunter\JuniperMist\Apis\SitesStatsClientsWirelessApi;
use Iahunter\JuniperMist\Apis\SitesStatsDevicesApi;
use Iahunter\JuniperMist\Apis\SitesStatsDiscoveredSwitchesApi;
use Iahunter\JuniperMist\Apis\SitesStatsClientsSdkApi;
use Iahunter\JuniperMist\Apis\SitesStatsMxedgesApi;
use Iahunter\JuniperMist\Apis\SitesStatsPortsApi;
use Iahunter\JuniperMist\Apis\SitesStatsZonesApi;
use Iahunter\JuniperMist\Apis\SitesStatsWxrulesApi;
use Iahunter\JuniperMist\Apis\SitesUiSettingsApi;
use Iahunter\JuniperMist\Apis\SitesVbeaconsApi;
use Iahunter\JuniperMist\Apis\SitesVpnsApi;
use Iahunter\JuniperMist\Apis\SitesClientsWanApi;
use Iahunter\JuniperMist\Apis\SitesWanUsagesApi;
use Iahunter\JuniperMist\Apis\SitesWebhooksApi;
use Iahunter\JuniperMist\Apis\SitesClientsWiredApi;
use Iahunter\JuniperMist\Apis\SitesWlansApi;
use Iahunter\JuniperMist\Apis\SitesWxrulesApi;
use Iahunter\JuniperMist\Apis\SitesWxtagsApi;
use Iahunter\JuniperMist\Apis\SitesWxtunnelsApi;
use Iahunter\JuniperMist\Apis\SitesZonesApi;
use Iahunter\JuniperMist\Apis\SamplesWebhooksApi;

class Client
{
    private HttpClient $http;
    public ConstantsEventsApi $constants_events;
    public ConstantsDefinitionsApi $constants_definitions;
    public ConstantsModelsApi $constants_models;
    public InstallerApi $installer;
    public AdminsApi $admins;
    public AdminsLoginApi $admins_login;
    public AdminsLookupApi $admins_lookup;
    public AdminsLoginOauth2Api $admins_login___oauth2;
    public AdminsLogoutApi $admins_logout;
    public OrgsSdkInvitesApi $orgs_sdk_invites;
    public MspsApi $msps;
    public MspsAdminsApi $msps_admins;
    public MspsLicensesApi $msps_licenses;
    public MspsSlesApi $msps_sles;
    public MspsInventoryApi $msps_inventory;
    public MspsLogoApi $msps_logo;
    public MspsLogsApi $msps_logs;
    public MspsOrgGroupsApi $msps_org_groups;
    public MspsOrgsApi $msps_orgs;
    public MspsSsoRolesApi $msps_sso_roles;
    public MspsSsoApi $msps_sso;
    public MspsMarvisApi $msps_marvis;
    public MspsTicketsApi $msps_tickets;
    public OrgsApi $orgs;
    public OrgsDevicesSsrApi $orgs_devices___ssr;
    public OrgsAdvancedAntiMalwareProfilesApi $orgs_advanced_anti_malware_profiles;
    public OrgsAdminsApi $orgs_admins;
    public OrgsAlarmsApi $orgs_alarms;
    public OrgsAlarmTemplatesApi $orgs_alarm_templates;
    public OrgsApiTokensApi $orgs_api_tokens;
    public OrgsApTemplatesApi $orgs_ap_templates;
    public OrgsAssetFiltersApi $orgs_asset_filters;
    public OrgsAssetsApi $orgs_assets;
    public OrgsAntivirusProfilesApi $orgs_antivirus_profiles;
    public OrgsCertApi $orgs_cert;
    public OrgsLicensesApi $orgs_licenses;
    public OrgsClientsWirelessApi $orgs_clients___wireless;
    public UtilitiesWiFiApi $utilities_wi_fi;
    public OrgsCrlApi $orgs_crl;
    public OrgsDeviceProfilesApi $orgs_device_profiles;
    public OrgsDevicesApi $orgs_devices;
    public UtilitiesUpgradeApi $utilities_upgrade;
    public OrgsEventsApi $orgs_events;
    public OrgsEvpnTopologiesApi $orgs_evpn_topologies;
    public OrgsGatewayTemplatesApi $orgs_gateway_templates;
    public OrgsGuestsApi $orgs_guests;
    public OrgsIdpProfilesApi $orgs_idp_profiles;
    public OrgsSlesApi $orgs_sles;
    public OrgsInventoryApi $orgs_inventory;
    public OrgsJsiApi $orgs_jsi;
    public OrgsLogsApi $orgs_logs;
    public OrgsMapsApi $orgs_maps;
    public OrgsMarvisInvitesApi $orgs_marvis_invites;
    public OrgsNacIdpApi $orgs_nac_idp;
    public OrgsMxclustersApi $orgs_mxclusters;
    public OrgsMxedgesApi $orgs_mxedges;
    public OrgsMxtunnelsApi $orgs_mxtunnels;
    public OrgsClientsNacApi $orgs_clients___nac;
    public OrgsNacPortalsApi $orgs_nac_portals;
    public OrgsNacRulesApi $orgs_nac_rules;
    public OrgsNacTagsApi $orgs_nac_tags;
    public OrgsNetworksApi $orgs_networks;
    public OrgsNetworkTemplatesApi $orgs_network_templates;
    public OrgsDevicesOthersApi $orgs_devices___others;
    public UtilitiesPcapsApi $utilities_pcaps;
    public OrgsPremiumAnalyticsApi $orgs_premium_analytics;
    public OrgsPskPortalsApi $orgs_psk_portals;
    public OrgsPsksApi $orgs_psks;
    public OrgsRfTemplatesApi $orgs_rf_templates;
    public OrgsClientsSdkApi $orgs_clients___sdk;
    public OrgsSdkTemplatesApi $orgs_sdk_templates;
    public OrgsSecintelProfilesApi $orgs_secintel_profiles;
    public OrgsSecurityPoliciesApi $orgs_security_policies;
    public OrgsServicePoliciesApi $orgs_service_policies;
    public OrgsServicesApi $orgs_services;
    public OrgsSettingApi $orgs_setting;
    public OrgsIntegrationCradlepointApi $orgs_integration_cradlepoint;
    public OrgsIntegrationJseApi $orgs_integration_jse;
    public OrgsIntegrationJuniperApi $orgs_integration_juniper;
    public OrgsNacCrlApi $orgs_nac_crl;
    public OrgsScepApi $orgs_scep;
    public OrgsIntegrationSkyatpApi $orgs_integration_skyatp;
    public OrgsIntegrationZscalerApi $orgs_integration_zscaler;
    public OrgsLinkedApplicationsApi $orgs_linked_applications;
    public OrgsSitegroupsApi $orgs_sitegroups;
    public OrgsSitesApi $orgs_sites;
    public OrgsSiteTemplatesApi $orgs_site_templates;
    public OrgsSsoRolesApi $orgs_sso_roles;
    public OrgsSsoApi $orgs_sso;
    public OrgsStatsApi $orgs_stats;
    public OrgsStatsAssetsApi $orgs_stats___assets;
    public OrgsStatsBgpPeersApi $orgs_stats___bgp_peers;
    public OrgsStatsDevicesApi $orgs_stats___devices;
    public OrgsClientsMarvisApi $orgs_clients___marvis;
    public OrgsStatsMxedgesApi $orgs_stats___mxedges;
    public OrgsStatsOtherDevicesApi $orgs_stats___other_devices;
    public OrgsStatsPortsApi $orgs_stats___ports;
    public OrgsStatsSitesApi $orgs_stats___sites;
    public OrgsStatsTunnelsApi $orgs_stats___tunnels;
    public OrgsStatsVpnPeersApi $orgs_stats___vpn_peers;
    public OrgsWlanTemplatesApi $orgs_wlan_templates;
    public OrgsTicketsApi $orgs_tickets;
    public OrgsMarvisApi $orgs_marvis;
    public OrgsUiSettingsApi $orgs_ui_settings;
    public OrgsUserMacsApi $orgs_user_macs;
    public OrgsVarsApi $orgs_vars;
    public OrgsVpnsApi $orgs_vpns;
    public OrgsClientsWanApi $orgs_clients___wan;
    public OrgsWebhooksApi $orgs_webhooks;
    public OrgsClientsWiredApi $orgs_clients___wired;
    public UtilitiesLanApi $utilities_lan;
    public OrgsWlansApi $orgs_wlans;
    public OrgsWxrulesApi $orgs_wxrules;
    public OrgsWxtagsApi $orgs_wxtags;
    public OrgsWxtunnelsApi $orgs_wxtunnels;
    public AdminsRecoverPasswordApi $admins_recover_password;
    public SelfAccountApi $self_account;
    public SelfApiTokenApi $self_api_token;
    public SelfAuditLogsApi $self_audit_logs;
    public SelfOauth2Api $self_oauth2;
    public SelfAlarmsApi $self_alarms;
    public SelfMfaApi $self_mfa;
    public SitesApi $sites;
    public SitesAdvancedAntiMalwareProfilesApi $sites_advanced_anti_malware_profiles;
    public SitesAlarmsApi $sites_alarms;
    public SitesSpectrumAnalysisApi $sites_spectrum_analysis;
    public SitesAnomalyApi $sites_anomaly;
    public SitesApplicationsApi $sites_applications;
    public SitesApTemplatesApi $sites_ap_templates;
    public SitesAssetFiltersApi $sites_asset_filters;
    public SitesAssetsApi $sites_assets;
    public SitesAntivirusProfilesApi $sites_antivirus_profiles;
    public SitesBeaconsApi $sites_beacons;
    public SitesClientsWirelessApi $sites_clients___wireless;
    public SitesDeviceProfilesApi $sites_device_profiles;
    public SitesDevicesApi $sites_devices;
    public SitesDevicesWirelessApi $sites_devices___wireless;
    public UtilitiesCommonApi $utilities_common;
    public UtilitiesLocationApi $utilities_location;
    public SitesSyntheticTestsApi $sites_synthetic_tests;
    public UtilitiesWanApi $utilities_wan;
    public SitesDevicesWanClusterApi $sites_devices___wan_cluster;
    public SitesDevicesWiredApi $sites_devices___wired;
    public SitesDevicesWiredVirtualChassisApi $sites_devices___wired___virtual_chassis;
    public SitesEventsApi $sites_events;
    public SitesEvpnTopologiesApi $sites_evpn_topologies;
    public SitesGatewayTemplatesApi $sites_gateway_templates;
    public SitesGuestsApi $sites_guests;
    public SitesIdpProfilesApi $sites_idp_profiles;
    public SitesInsightsApi $sites_insights;
    public OrgsNacFingerprintsApi $orgs_nac_fingerprints;
    public SitesRoguesApi $sites_rogues;
    public SitesLicensesApi $sites_licenses;
    public SitesLocationApi $sites_location;
    public SitesMapsApi $sites_maps;
    public SitesMapsAutoPlacementApi $sites_maps___auto_placement;
    public SitesMapsAutoZoneApi $sites_maps___auto_zone;
    public SitesMxedgesApi $sites_mxedges;
    public UtilitiesMxedgeApi $utilities_mxedge;
    public SitesClientsNacApi $sites_clients___nac;
    public SitesNetworksApi $sites_networks;
    public SitesNetworkTemplatesApi $sites_network_templates;
    public SitesDevicesOthersApi $sites_devices___others;
    public SitesPsksApi $sites_psks;
    public SitesRfdiagsApi $sites_rfdiags;
    public SitesRfTemplatesApi $sites_rf_templates;
    public SitesRrmApi $sites_rrm;
    public SitesRssiZonesApi $sites_rssi_zones;
    public SitesSecintelProfilesApi $sites_secintel_profiles;
    public SitesServicePoliciesApi $sites_service_policies;
    public SitesServicesApi $sites_services;
    public SitesSettingApi $sites_setting;
    public SitesJseApi $sites_jse;
    public SitesSiteTemplatesApi $sites_site_templates;
    public SitesSkyatpApi $sites_skyatp;
    public SitesSlesApi $sites_sles;
    public SitesStatsApi $sites_stats;
    public SitesStatsAppsApi $sites_stats___apps;
    public SitesStatsAssetsApi $sites_stats___assets;
    public SitesStatsBeaconsApi $sites_stats___beacons;
    public SitesStatsBgpPeersApi $sites_stats___bgp_peers;
    public SitesStatsCallsApi $sites_stats___calls;
    public SitesStatsClientsWirelessApi $sites_stats___clients_wireless;
    public SitesStatsDevicesApi $sites_stats___devices;
    public SitesStatsDiscoveredSwitchesApi $sites_stats___discovered_switches;
    public SitesStatsClientsSdkApi $sites_stats___clients_sdk;
    public SitesStatsMxedgesApi $sites_stats___mxedges;
    public SitesStatsPortsApi $sites_stats___ports;
    public SitesStatsZonesApi $sites_stats___zones;
    public SitesStatsWxrulesApi $sites_stats___wxrules;
    public SitesUiSettingsApi $sites_ui_settings;
    public SitesVbeaconsApi $sites_vbeacons;
    public SitesVpnsApi $sites_vpns;
    public SitesClientsWanApi $sites_clients___wan;
    public SitesWanUsagesApi $sites_wan_usages;
    public SitesWebhooksApi $sites_webhooks;
    public SitesClientsWiredApi $sites_clients___wired;
    public SitesWlansApi $sites_wlans;
    public SitesWxrulesApi $sites_wxrules;
    public SitesWxtagsApi $sites_wxtags;
    public SitesWxtunnelsApi $sites_wxtunnels;
    public SitesZonesApi $sites_zones;
    public SamplesWebhooksApi $samples_webhooks;

    public function __construct(string $apiToken, string $baseUri = 'https://api.mist.com/api/v1/', array $opts = [])
    {
        $this->http = new HttpClient($baseUri, $apiToken, $opts);
        $this->constants_events = new ConstantsEventsApi($this->http);
        $this->constants_definitions = new ConstantsDefinitionsApi($this->http);
        $this->constants_models = new ConstantsModelsApi($this->http);
        $this->installer = new InstallerApi($this->http);
        $this->admins = new AdminsApi($this->http);
        $this->admins_login = new AdminsLoginApi($this->http);
        $this->admins_lookup = new AdminsLookupApi($this->http);
        $this->admins_login___oauth2 = new AdminsLoginOauth2Api($this->http);
        $this->admins_logout = new AdminsLogoutApi($this->http);
        $this->orgs_sdk_invites = new OrgsSdkInvitesApi($this->http);
        $this->msps = new MspsApi($this->http);
        $this->msps_admins = new MspsAdminsApi($this->http);
        $this->msps_licenses = new MspsLicensesApi($this->http);
        $this->msps_sles = new MspsSlesApi($this->http);
        $this->msps_inventory = new MspsInventoryApi($this->http);
        $this->msps_logo = new MspsLogoApi($this->http);
        $this->msps_logs = new MspsLogsApi($this->http);
        $this->msps_org_groups = new MspsOrgGroupsApi($this->http);
        $this->msps_orgs = new MspsOrgsApi($this->http);
        $this->msps_sso_roles = new MspsSsoRolesApi($this->http);
        $this->msps_sso = new MspsSsoApi($this->http);
        $this->msps_marvis = new MspsMarvisApi($this->http);
        $this->msps_tickets = new MspsTicketsApi($this->http);
        $this->orgs = new OrgsApi($this->http);
        $this->orgs_devices___ssr = new OrgsDevicesSsrApi($this->http);
        $this->orgs_advanced_anti_malware_profiles = new OrgsAdvancedAntiMalwareProfilesApi($this->http);
        $this->orgs_admins = new OrgsAdminsApi($this->http);
        $this->orgs_alarms = new OrgsAlarmsApi($this->http);
        $this->orgs_alarm_templates = new OrgsAlarmTemplatesApi($this->http);
        $this->orgs_api_tokens = new OrgsApiTokensApi($this->http);
        $this->orgs_ap_templates = new OrgsApTemplatesApi($this->http);
        $this->orgs_asset_filters = new OrgsAssetFiltersApi($this->http);
        $this->orgs_assets = new OrgsAssetsApi($this->http);
        $this->orgs_antivirus_profiles = new OrgsAntivirusProfilesApi($this->http);
        $this->orgs_cert = new OrgsCertApi($this->http);
        $this->orgs_licenses = new OrgsLicensesApi($this->http);
        $this->orgs_clients___wireless = new OrgsClientsWirelessApi($this->http);
        $this->utilities_wi_fi = new UtilitiesWiFiApi($this->http);
        $this->orgs_crl = new OrgsCrlApi($this->http);
        $this->orgs_device_profiles = new OrgsDeviceProfilesApi($this->http);
        $this->orgs_devices = new OrgsDevicesApi($this->http);
        $this->utilities_upgrade = new UtilitiesUpgradeApi($this->http);
        $this->orgs_events = new OrgsEventsApi($this->http);
        $this->orgs_evpn_topologies = new OrgsEvpnTopologiesApi($this->http);
        $this->orgs_gateway_templates = new OrgsGatewayTemplatesApi($this->http);
        $this->orgs_guests = new OrgsGuestsApi($this->http);
        $this->orgs_idp_profiles = new OrgsIdpProfilesApi($this->http);
        $this->orgs_sles = new OrgsSlesApi($this->http);
        $this->orgs_inventory = new OrgsInventoryApi($this->http);
        $this->orgs_jsi = new OrgsJsiApi($this->http);
        $this->orgs_logs = new OrgsLogsApi($this->http);
        $this->orgs_maps = new OrgsMapsApi($this->http);
        $this->orgs_marvis_invites = new OrgsMarvisInvitesApi($this->http);
        $this->orgs_nac_idp = new OrgsNacIdpApi($this->http);
        $this->orgs_mxclusters = new OrgsMxclustersApi($this->http);
        $this->orgs_mxedges = new OrgsMxedgesApi($this->http);
        $this->orgs_mxtunnels = new OrgsMxtunnelsApi($this->http);
        $this->orgs_clients___nac = new OrgsClientsNacApi($this->http);
        $this->orgs_nac_portals = new OrgsNacPortalsApi($this->http);
        $this->orgs_nac_rules = new OrgsNacRulesApi($this->http);
        $this->orgs_nac_tags = new OrgsNacTagsApi($this->http);
        $this->orgs_networks = new OrgsNetworksApi($this->http);
        $this->orgs_network_templates = new OrgsNetworkTemplatesApi($this->http);
        $this->orgs_devices___others = new OrgsDevicesOthersApi($this->http);
        $this->utilities_pcaps = new UtilitiesPcapsApi($this->http);
        $this->orgs_premium_analytics = new OrgsPremiumAnalyticsApi($this->http);
        $this->orgs_psk_portals = new OrgsPskPortalsApi($this->http);
        $this->orgs_psks = new OrgsPsksApi($this->http);
        $this->orgs_rf_templates = new OrgsRfTemplatesApi($this->http);
        $this->orgs_clients___sdk = new OrgsClientsSdkApi($this->http);
        $this->orgs_sdk_templates = new OrgsSdkTemplatesApi($this->http);
        $this->orgs_secintel_profiles = new OrgsSecintelProfilesApi($this->http);
        $this->orgs_security_policies = new OrgsSecurityPoliciesApi($this->http);
        $this->orgs_service_policies = new OrgsServicePoliciesApi($this->http);
        $this->orgs_services = new OrgsServicesApi($this->http);
        $this->orgs_setting = new OrgsSettingApi($this->http);
        $this->orgs_integration_cradlepoint = new OrgsIntegrationCradlepointApi($this->http);
        $this->orgs_integration_jse = new OrgsIntegrationJseApi($this->http);
        $this->orgs_integration_juniper = new OrgsIntegrationJuniperApi($this->http);
        $this->orgs_nac_crl = new OrgsNacCrlApi($this->http);
        $this->orgs_scep = new OrgsScepApi($this->http);
        $this->orgs_integration_skyatp = new OrgsIntegrationSkyatpApi($this->http);
        $this->orgs_integration_zscaler = new OrgsIntegrationZscalerApi($this->http);
        $this->orgs_linked_applications = new OrgsLinkedApplicationsApi($this->http);
        $this->orgs_sitegroups = new OrgsSitegroupsApi($this->http);
        $this->orgs_sites = new OrgsSitesApi($this->http);
        $this->orgs_site_templates = new OrgsSiteTemplatesApi($this->http);
        $this->orgs_sso_roles = new OrgsSsoRolesApi($this->http);
        $this->orgs_sso = new OrgsSsoApi($this->http);
        $this->orgs_stats = new OrgsStatsApi($this->http);
        $this->orgs_stats___assets = new OrgsStatsAssetsApi($this->http);
        $this->orgs_stats___bgp_peers = new OrgsStatsBgpPeersApi($this->http);
        $this->orgs_stats___devices = new OrgsStatsDevicesApi($this->http);
        $this->orgs_clients___marvis = new OrgsClientsMarvisApi($this->http);
        $this->orgs_stats___mxedges = new OrgsStatsMxedgesApi($this->http);
        $this->orgs_stats___other_devices = new OrgsStatsOtherDevicesApi($this->http);
        $this->orgs_stats___ports = new OrgsStatsPortsApi($this->http);
        $this->orgs_stats___sites = new OrgsStatsSitesApi($this->http);
        $this->orgs_stats___tunnels = new OrgsStatsTunnelsApi($this->http);
        $this->orgs_stats___vpn_peers = new OrgsStatsVpnPeersApi($this->http);
        $this->orgs_wlan_templates = new OrgsWlanTemplatesApi($this->http);
        $this->orgs_tickets = new OrgsTicketsApi($this->http);
        $this->orgs_marvis = new OrgsMarvisApi($this->http);
        $this->orgs_ui_settings = new OrgsUiSettingsApi($this->http);
        $this->orgs_user_macs = new OrgsUserMacsApi($this->http);
        $this->orgs_vars = new OrgsVarsApi($this->http);
        $this->orgs_vpns = new OrgsVpnsApi($this->http);
        $this->orgs_clients___wan = new OrgsClientsWanApi($this->http);
        $this->orgs_webhooks = new OrgsWebhooksApi($this->http);
        $this->orgs_clients___wired = new OrgsClientsWiredApi($this->http);
        $this->utilities_lan = new UtilitiesLanApi($this->http);
        $this->orgs_wlans = new OrgsWlansApi($this->http);
        $this->orgs_wxrules = new OrgsWxrulesApi($this->http);
        $this->orgs_wxtags = new OrgsWxtagsApi($this->http);
        $this->orgs_wxtunnels = new OrgsWxtunnelsApi($this->http);
        $this->admins_recover_password = new AdminsRecoverPasswordApi($this->http);
        $this->self_account = new SelfAccountApi($this->http);
        $this->self_api_token = new SelfApiTokenApi($this->http);
        $this->self_audit_logs = new SelfAuditLogsApi($this->http);
        $this->self_oauth2 = new SelfOauth2Api($this->http);
        $this->self_alarms = new SelfAlarmsApi($this->http);
        $this->self_mfa = new SelfMfaApi($this->http);
        $this->sites = new SitesApi($this->http);
        $this->sites_advanced_anti_malware_profiles = new SitesAdvancedAntiMalwareProfilesApi($this->http);
        $this->sites_alarms = new SitesAlarmsApi($this->http);
        $this->sites_spectrum_analysis = new SitesSpectrumAnalysisApi($this->http);
        $this->sites_anomaly = new SitesAnomalyApi($this->http);
        $this->sites_applications = new SitesApplicationsApi($this->http);
        $this->sites_ap_templates = new SitesApTemplatesApi($this->http);
        $this->sites_asset_filters = new SitesAssetFiltersApi($this->http);
        $this->sites_assets = new SitesAssetsApi($this->http);
        $this->sites_antivirus_profiles = new SitesAntivirusProfilesApi($this->http);
        $this->sites_beacons = new SitesBeaconsApi($this->http);
        $this->sites_clients___wireless = new SitesClientsWirelessApi($this->http);
        $this->sites_device_profiles = new SitesDeviceProfilesApi($this->http);
        $this->sites_devices = new SitesDevicesApi($this->http);
        $this->sites_devices___wireless = new SitesDevicesWirelessApi($this->http);
        $this->utilities_common = new UtilitiesCommonApi($this->http);
        $this->utilities_location = new UtilitiesLocationApi($this->http);
        $this->sites_synthetic_tests = new SitesSyntheticTestsApi($this->http);
        $this->utilities_wan = new UtilitiesWanApi($this->http);
        $this->sites_devices___wan_cluster = new SitesDevicesWanClusterApi($this->http);
        $this->sites_devices___wired = new SitesDevicesWiredApi($this->http);
        $this->sites_devices___wired___virtual_chassis = new SitesDevicesWiredVirtualChassisApi($this->http);
        $this->sites_events = new SitesEventsApi($this->http);
        $this->sites_evpn_topologies = new SitesEvpnTopologiesApi($this->http);
        $this->sites_gateway_templates = new SitesGatewayTemplatesApi($this->http);
        $this->sites_guests = new SitesGuestsApi($this->http);
        $this->sites_idp_profiles = new SitesIdpProfilesApi($this->http);
        $this->sites_insights = new SitesInsightsApi($this->http);
        $this->orgs_nac_fingerprints = new OrgsNacFingerprintsApi($this->http);
        $this->sites_rogues = new SitesRoguesApi($this->http);
        $this->sites_licenses = new SitesLicensesApi($this->http);
        $this->sites_location = new SitesLocationApi($this->http);
        $this->sites_maps = new SitesMapsApi($this->http);
        $this->sites_maps___auto_placement = new SitesMapsAutoPlacementApi($this->http);
        $this->sites_maps___auto_zone = new SitesMapsAutoZoneApi($this->http);
        $this->sites_mxedges = new SitesMxedgesApi($this->http);
        $this->utilities_mxedge = new UtilitiesMxedgeApi($this->http);
        $this->sites_clients___nac = new SitesClientsNacApi($this->http);
        $this->sites_networks = new SitesNetworksApi($this->http);
        $this->sites_network_templates = new SitesNetworkTemplatesApi($this->http);
        $this->sites_devices___others = new SitesDevicesOthersApi($this->http);
        $this->sites_psks = new SitesPsksApi($this->http);
        $this->sites_rfdiags = new SitesRfdiagsApi($this->http);
        $this->sites_rf_templates = new SitesRfTemplatesApi($this->http);
        $this->sites_rrm = new SitesRrmApi($this->http);
        $this->sites_rssi_zones = new SitesRssiZonesApi($this->http);
        $this->sites_secintel_profiles = new SitesSecintelProfilesApi($this->http);
        $this->sites_service_policies = new SitesServicePoliciesApi($this->http);
        $this->sites_services = new SitesServicesApi($this->http);
        $this->sites_setting = new SitesSettingApi($this->http);
        $this->sites_jse = new SitesJseApi($this->http);
        $this->sites_site_templates = new SitesSiteTemplatesApi($this->http);
        $this->sites_skyatp = new SitesSkyatpApi($this->http);
        $this->sites_sles = new SitesSlesApi($this->http);
        $this->sites_stats = new SitesStatsApi($this->http);
        $this->sites_stats___apps = new SitesStatsAppsApi($this->http);
        $this->sites_stats___assets = new SitesStatsAssetsApi($this->http);
        $this->sites_stats___beacons = new SitesStatsBeaconsApi($this->http);
        $this->sites_stats___bgp_peers = new SitesStatsBgpPeersApi($this->http);
        $this->sites_stats___calls = new SitesStatsCallsApi($this->http);
        $this->sites_stats___clients_wireless = new SitesStatsClientsWirelessApi($this->http);
        $this->sites_stats___devices = new SitesStatsDevicesApi($this->http);
        $this->sites_stats___discovered_switches = new SitesStatsDiscoveredSwitchesApi($this->http);
        $this->sites_stats___clients_sdk = new SitesStatsClientsSdkApi($this->http);
        $this->sites_stats___mxedges = new SitesStatsMxedgesApi($this->http);
        $this->sites_stats___ports = new SitesStatsPortsApi($this->http);
        $this->sites_stats___zones = new SitesStatsZonesApi($this->http);
        $this->sites_stats___wxrules = new SitesStatsWxrulesApi($this->http);
        $this->sites_ui_settings = new SitesUiSettingsApi($this->http);
        $this->sites_vbeacons = new SitesVbeaconsApi($this->http);
        $this->sites_vpns = new SitesVpnsApi($this->http);
        $this->sites_clients___wan = new SitesClientsWanApi($this->http);
        $this->sites_wan_usages = new SitesWanUsagesApi($this->http);
        $this->sites_webhooks = new SitesWebhooksApi($this->http);
        $this->sites_clients___wired = new SitesClientsWiredApi($this->http);
        $this->sites_wlans = new SitesWlansApi($this->http);
        $this->sites_wxrules = new SitesWxrulesApi($this->http);
        $this->sites_wxtags = new SitesWxtagsApi($this->http);
        $this->sites_wxtunnels = new SitesWxtunnelsApi($this->http);
        $this->sites_zones = new SitesZonesApi($this->http);
        $this->samples_webhooks = new SamplesWebhooksApi($this->http);
    }

    public function getHttp(): HttpClient { return $this->http; }
}